service: hooligan

custom:
  settings:
    USER_STREAMS_TABLE: userStreams

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom.settings}
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.USER_STREAMS_TABLE}"

functions:
  logStream:
    handler: handler.logStream
    events:
      - http:
          path: /stream
          method: post

resources:
  Resources:
    UserStreamsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "streamId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "streamId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.USER_STREAMS_TABLE}


